import Head from "next/head";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { PRODUCTS_URL } from "~src/url";
import FirstPage from "../components/firstpage/FirstPage";
import Navbar from "../components/firstpage/navbar/Navbar";

export default function Home({ products }) {

  const dispatch = useDispatch();
  useEffect(() => {
    const getData = async () => {
      const response = await fetch(PRODUCTS_URL);
      const data = await response.json();
      dispatch({ type: "getData", payload: data });
    }

    getData()
  }, []);

  return (
    <div>
      <Head>
        <title>Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <FirstPage />
    </div>
  );
}

// export const getServerSideProps = async (ctx) => {


//   const response = await fetch(PRODUCTS_URL);
//   const data = await response.json();

  
//   return {
//     props: {
//       products: data,
//     },
//   };
// };
